# Generated by Django 4.2.3 on 2023-10-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='user_email',
            new_name='user',
        ),
    ]
