# Generated by Django 4.2.3 on 2023-10-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Имя категории', max_length=128, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Имя категории', max_length=128, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_comment_en_us',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_comment_ru',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_type_en_us',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=2, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_type_ru',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=2, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Имя категории', max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryPost',
            field=models.ManyToManyField(related_name='category', through='news.PostCategory', to='news.category', verbose_name='This is the help text'),
        ),
    ]
