# Generated by Django 4.2.3 on 2023-10-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_type_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_type_ru',
        ),
    ]
