# Generated by Django 4.2.3 on 2023-09-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_parent_alter_author_author_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_create']},
        ),
    ]
