# Generated by Django 4.2.3 on 2023-08-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_author_user_alter_author_ratting_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
