# Generated by Django 4.2.3 on 2023-08-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_category',
            new_name='categoryPost',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ratting_post',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг поста'),
        ),
    ]
