# Generated by Django 4.2.3 on 2023-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename__category_post_categorypost_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='namePost',
            field=models.ManyToManyField(through='news.PostCategory', to='news.post'),
        ),
    ]
